GET http://localhost:5253/games
###
GET http://localhost:5253/games/4
###
POST http://localhost:5253/games
Content-Type: application/json

{
    "name":"spider man",
    "genre": "Epic",
    "type": 2009, 
    "releaseDate": "2009-06-06"
}
###
PUT http://localhost:5253/games/2
Content-Type:  application/json

  {
    "id": 2,
    "name": "Mortal Combact 4",
    "genre": "Fight",
    "type": 4,
    "releaseDate": "1999-11-01"
  },
###
DELETE http://localhost:5253/games/1
