GET http://localhost:5253/games
###
GET http://localhost:5253/games/4
###
POST http://localhost:5253/games
Content-Type: application/json

{
    "name":"spider man",
    "genre": "Epic",
    "type":  90, 
    "releaseDate": "2009-06-06"
}
###
PUT http://localhost:5253/games/2
Content-Type:  application/json

{
    "name":"spider man",
    "genre": "Epic",
    "type":  9000, 
    "releaseDate": "2009-06-06"
}
###
DELETE http://localhost:5253/games/1
